### ISSUE TITLE
Hi friend

### ISSUE THREAD

**Issue by agunes77** [individual61/pov-stick#1]
![img_6209](https://user-images.githubusercontent.com/6403981/47129183-ee53ca80-d29c-11e8-8258-4eeee88582f1.jpg)

**Comment by agunes77** [comment]
Hi

platformio for atom install + fastLED.h lib install
main.cpp compile and upload success
but image how to install plase help me

I am grateful for the project

Sincerely

**Comment by individual61** [comment]
Hi,

Thank you for taking an interest in my project. Honestly I did not expect anyone to use it, and I placed the files on github mostly for myself. I'll see if I can help you, though.

Note that you have opened this issue on the wrong repository. Please use

https://github.com/individual61/pov-stick-5050

in future.

In main.cpp, see Line 63:

`const uint8_t image[] = `

That is where the image goes.

**Comment by agunes77** [comment]
Hello there

Thank you

For your work

My e-mail address: agunesxt@gmail.com

Can we develop the project
Sample
Micro sd module
Wifi or bluetoth support
144 led / meter led strip support

Sincerely

**Comment by individual61** [comment]
Thank you for your interest, but I am not available to help with your particular project. I wish you the best of luck, though!
